// Ambient module declarations that don't depend on expo-env.d.ts (which is
// managed/regenerated by Expo tooling and has been observed disappearing
// from the working tree locally). Keeping this here means the CSS
// side-effect import in MapScreen.web.tsx (`import "leaflet/dist/leaflet.css"`)
// type-checks regardless of that file's state.
declare module "*.css";
